import { StyleSheet } from "react-native";

export const COLORS = {
  primary: "#e41f07",
  secondary: "#ffa201",
  bgBody: "#f7f8f9",
  border: "#e8e8e8",
  white: "#fff",
  text: "#1f2020",
  textGray: "#707070",
  textLight: "#9ca3af",
  danger: "#ef1e1e",
  success: "#28a745",
  info: "#17a2b8",
  warning: "#ffc107",
  dark: "#343a40",
  inputBg: "#fff",
  inputDisabled: "#f3f4f6",
  bgBackdrop: "rgba(0,0,0,0.5)",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgBody,
  },
  toolbar: {
    flexDirection: "row",
    padding: 16,
    gap: 12,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    alignItems: "center",
  },

  cardContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    borderLeftWidth: 5,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.text,
    flex: 1,
    marginRight: 8,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: COLORS.white,
  },
  cardBody: {
    padding: 12,
    gap: 10,
  },
  voucherCodeContainer: {
    backgroundColor: "#fcfcfc",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#dee2e6",
    borderStyle: "dashed",
    alignSelf: "flex-start",
    marginBottom: 4,
  },
  voucherCode: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.primary,
    letterSpacing: 0.5,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoText: {
    fontSize: 13,
    color: COLORS.textGray,
    flex: 1,
  },
  highlightText: {
    color: "#333",
    fontWeight: "600",
  },
  cardFooter: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
    gap: 6,
  },
  separator: {
    width: 1,
    backgroundColor: "#f0f0f0",
    marginVertical: 10,
  },
  actionText: {
    fontSize: 13,
    fontWeight: "500",
  },

  centeredView: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: COLORS.bgBackdrop },
  keyboardView: { width: "100%", alignItems: "center", height: "100%", justifyContent: "center" },
  modalView: { width: "95%", maxHeight: "84%", backgroundColor: "white", borderRadius: 12, overflow: "hidden", shadowColor: "#000", elevation: 5 },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: { fontSize: 18, fontWeight: "600", color: COLORS.text, flex: 0 },
  closeIcon: { padding: 4 },
  modalBody: { padding: 20 },
  formGroup: { marginBottom: 16 },
  row: { flexDirection: "row", gap: 12 },
  col: { flex: 1 },
  label: { fontSize: 14, fontWeight: "500", marginBottom: 6, color: COLORS.text },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.inputBg,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: COLORS.text,
  },
  inputDisabled: { backgroundColor: COLORS.inputDisabled, color: COLORS.textGray },

  radioContainer: { flexDirection: "row", gap: 16, marginTop: 4 },
  radioItem: { flexDirection: "row", alignItems: "center", gap: 6 },

  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    padding: 10,
    backgroundColor: COLORS.inputBg,
  },

  deleteContainer: { alignItems: "center", padding: 20, paddingTop: 40 },
  confirmText: { fontSize: 16, textAlign: "center", marginTop: 16, marginBottom: 8, color: COLORS.text },
  subText: { fontSize: 14, color: COLORS.textGray, textAlign: "center" },
  modalFooter: { flexDirection: "row", justifyContent: "flex-end", padding: 16, borderTopWidth: 1, borderTopColor: COLORS.border, gap: 12 },
  button: { borderRadius: 6, paddingVertical: 10, paddingHorizontal: 16, minWidth: 90, alignItems: "center", justifyContent: "center" },
  buttonClose: { backgroundColor: COLORS.inputBg, borderWidth: 1, borderColor: COLORS.border },
  buttonSave: { backgroundColor: COLORS.primary },
  buttonDelete: { backgroundColor: COLORS.danger },
  textStyle: { color: "white", fontWeight: "600", fontSize: 14 },
});
