export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  Home: undefined;
  ResourcesScreen: undefined;
  RolesPermissionsScreen: undefined;
  Permission: { roleId: number; roleName: string };
  BranchScreen: undefined;
  ManagerUsersScreen: undefined;
  CustomerSourceScreen: undefined;
  VoucherScreen: undefined;
  UnitScreen: undefined;
  CategoryScreen: undefined;
  ProductScreen: undefined;
  ServiceScreen: undefined;
  InvoiceScreen: undefined;
  CustomerSettingsScreen: undefined;
  CustomersScreen: undefined;
  CallHistoryScreen: undefined;
  ProfileSettingsScreen: undefined;
  CalendarScreen: undefined;
};
