import { StyleSheet, Platform, Dimensions } from "react-native";

export const COLORS = {
  primary: "#e41f07",
  secondary: "#ffa201",
  bgBody: "#f5f6fa",
  border: "#e8e8e8",
  white: "#fff",
  text: "#1f2020",
  textGray: "#707070",
  textLight: "#9ca3af",
  danger: "#ff3b30",
  success: "#34c759",
  info: "#007aff",
  warning: "#ffcc00",
  inputBg: "#fff",
  inputDisabled: "#f9f9f9",
  bgBackdrop: "rgba(0,0,0,0.6)",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgBody,
  },
  toolbar: {
    flexDirection: "row",
    padding: 16,
    gap: 12,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    alignItems: "center",
  },

  // --- MODAL LAYOUT ---
  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.bgBody,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: { fontSize: 17, fontWeight: "700", color: COLORS.text },
  modalBody: { padding: 16 },

  // --- ACCORDION LAYOUT (Giống Customer) ---
  accordionItem: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
  },
  accordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    backgroundColor: "#f8f9fa",
  },
  accordionTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.text,
    flex: 1,
    marginLeft: 10,
  },
  accordionContent: {
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: "#e3f2fd",
    alignItems: "center",
    justifyContent: "center",
  },

  // --- SECTIONS ---
  sectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.textGray,
    marginTop: 20,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // --- CUSTOMER CARD ---
  customerCardNew: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    position: "relative",
  },
  customerHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  customerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#e3f2fd",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  customerNameLarge: { fontSize: 16, fontWeight: "700", color: COLORS.text },
  customerCode: { fontSize: 12, color: COLORS.info, marginTop: 2, fontWeight: "600" },
  customerDetailRow: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  customerDetailText: { fontSize: 14, color: COLORS.textGray, marginLeft: 8 },
  changeCustomerBtnAbs: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: "#f5f5f5",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  changeBtnText: { fontSize: 12, fontWeight: "600", color: COLORS.primary },

  // --- ITEM CARD ---
  itemCard: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
  },
  itemImage: { width: 50, height: 50, borderRadius: 8, backgroundColor: "#f0f0f0", marginRight: 12 },
  itemInfo: { flex: 1 },
  itemName: { fontSize: 14, fontWeight: "600", color: COLORS.text, marginBottom: 4 },
  qtyBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginRight: 8,
  },
  qtyText: { color: "white", fontSize: 12, fontWeight: "700" },
  priceText: { fontSize: 14, fontWeight: "700", color: COLORS.text },
  deleteBtn: { padding: 8, marginLeft: 4 },

  // --- ADD BUTTONS ---
  actionButtonsContainer: { flexDirection: "row", gap: 12, marginBottom: 8 },

  // --- SUMMARY ---
  summaryContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 16,
  },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  summaryLabel: { fontSize: 14, color: COLORS.textGray },
  summaryValue: { fontSize: 14, fontWeight: "600", color: COLORS.text },
  divider: { height: 1, backgroundColor: COLORS.border, marginVertical: 12 },
  totalLabel: { fontSize: 16, fontWeight: "700", color: COLORS.text },
  totalValue: { fontSize: 18, fontWeight: "800", color: COLORS.primary },

  // --- EXTRAS ---
  cardContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 16,
  },
  voucherRow: { flexDirection: "row", gap: 8, alignItems: "center" },
  voucherInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
  },
  applyBtn: {
    backgroundColor: COLORS.text,
    height: 40,
    paddingHorizontal: 16,
    borderRadius: 6,
    justifyContent: "center",
  },
  applyBtnText: { color: "white", fontWeight: "600", fontSize: 13 },
  inputMulti: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: "#fff",
    borderRadius: 6,
    padding: 10,
    fontSize: 14,
    minHeight: 60,
    textAlignVertical: "top",
  },

  paymentRow: { flexDirection: "row", gap: 12, marginTop: 8 },
  paymentOption: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  paymentOptionActive: { borderColor: COLORS.primary, backgroundColor: "#fff5f5" },
  paymentText: { fontSize: 13, fontWeight: "600", color: COLORS.textGray },
  paymentTextActive: { color: COLORS.primary },

  // --- BOTTOM DOCK ---
  bottomDock: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 10,
  },
  dockTotal: { flex: 1 },
  dockLabel: { fontSize: 12, color: COLORS.textGray },
  dockValue: { fontSize: 18, fontWeight: "800", color: COLORS.primary },
  dockBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
    minWidth: 140,
  },
  dockBtnText: { color: "white", fontWeight: "700", fontSize: 16 },

  // --- DELETE MODAL ---
  centeredView: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: COLORS.bgBackdrop },
  modalView: { width: "100%", height: "100%", backgroundColor: COLORS.bgBody },
  deleteContainer: { alignItems: "center", padding: 20 },
  confirmText: { fontSize: 16, textAlign: "center", marginTop: 16, marginBottom: 8, fontWeight: "600", color: COLORS.text },
  subText: { fontSize: 14, color: COLORS.textGray, textAlign: "center", marginBottom: 20 },
  btnCancel: { flex: 1, padding: 12, borderRadius: 8, backgroundColor: "#f0f0f0", alignItems: "center" },
  btnDelete: { flex: 1, padding: 12, borderRadius: 8, backgroundColor: COLORS.danger, alignItems: "center" },
  emptyState: { alignItems: "center", paddingVertical: 40 },
  emptyText: { color: COLORS.textGray, marginTop: 8, fontSize: 14 },
});
