import { StyleSheet, Platform } from "react-native";

export const COLORS = {
  primary: "#e41f07",
  secondary: "#ffa201",
  bgBody: "#f5f6fa",
  border: "#e8e8e8",
  white: "#fff",
  text: "#1f2020",
  textGray: "#707070",
  textLight: "#9ca3af",
  danger: "#ff3b30",
  success: "#34c759",
  info: "#007aff",
  warning: "#ffcc00",
  inputBg: "#fff",
  inputDisabled: "#f9f9f9",
  bgBackdrop: "rgba(0,0,0,0.6)",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgBody,
  },
  toolbar: {
    flexDirection: "row",
    padding: 16,
    gap: 12,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    alignItems: "center",
  },

  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.bgBody,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: { fontSize: 17, fontWeight: "700", color: COLORS.text },
  modalBody: { padding: 16 },

  accordionItem: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
  },
  accordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    backgroundColor: "#f8f9fa",
  },
  accordionTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.text,
    flex: 1,
    marginLeft: 10,
  },
  accordionContent: {
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: "#e3f2fd",
    alignItems: "center",
    justifyContent: "center",
  },

  formGroup: { marginBottom: 16 },
  row: { flexDirection: "row", gap: 12 },
  col: { flex: 1 },
  label: { fontSize: 14, fontWeight: "600", marginBottom: 6, color: COLORS.text },

  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.inputBg,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: COLORS.text,
  },
  inputDisabled: { backgroundColor: COLORS.inputDisabled, color: COLORS.textGray },
  textArea: { height: 80, textAlignVertical: "top" },

  avatarSection: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  avatarPreview: {
    width: 80,
    height: 80,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    backgroundColor: "#f8f9fa",
  },
  avatarImg: { width: 80, height: 80, borderRadius: 8 },
  uploadBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#e3f2fd",
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  uploadText: { color: COLORS.info, fontWeight: "600", fontSize: 13 },

  radioGroup: { flexDirection: "row", gap: 16, marginTop: 4 },
  radioItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  radioLabel: { fontSize: 14, color: COLORS.text },

  attachmentBtn: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    backgroundColor: "#f8f9fa",
  },
  attachmentText: { marginLeft: 8, color: COLORS.info, fontSize: 14 },

  modalFooter: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    gap: 12,
    paddingBottom: 40,
    paddingTop: 16,
    paddingHorizontal: 16,
  },
  btnCancel: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: "#f1f3f5",
    alignItems: "center",
  },
  btnClose: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: "#f1f3f5",
    alignItems: "center",
  },
  btnSubmit: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    alignItems: "center",
  },
  btnText: { fontWeight: "700", fontSize: 15 },

  centeredView: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: COLORS.bgBackdrop },
  modalView: { width: "90%", backgroundColor: "white", borderRadius: 16, padding: 0 },
  deleteContainer: { alignItems: "center", padding: 24 },
  confirmText: { fontSize: 16, textAlign: "center", marginTop: 16, marginBottom: 8, fontWeight: "600", color: COLORS.text },
  subText: { fontSize: 14, color: COLORS.textGray, textAlign: "center", marginBottom: 20 },
  btnDelete: { flex: 1, padding: 12, borderRadius: 8, backgroundColor: COLORS.danger, alignItems: "center" },

  listAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#e9ecef",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  avatarText: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  emptyState: { alignItems: "center", paddingVertical: 40 },
  emptyText: { color: COLORS.textGray, marginTop: 8, fontSize: 14 },
});
